//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Common.Resources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error ingresando el elemento. Por favor intente de nuevo..
        /// </summary>
        public static string CreateErrorMessage {
            get {
                return ResourceManager.GetString("CreateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El elemento se creó correctamente..
        /// </summary>
        public static string CreateSuccessMessage {
            get {
                return ResourceManager.GetString("CreateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuerde que los campos númericos deben tener un máximo de 15 dígitos en la parte entera y 2 dígitos en la parte decimal.
        /// </summary>
        public static string DecimalFormatCorrect {
            get {
                return ResourceManager.GetString("DecimalFormatCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error, por favor intentarlo más tarde.
        /// </summary>
        public static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error borrando el elemento. Por favor intente de nuevo..
        /// </summary>
        public static string DeleteErrorMessage {
            get {
                return ResourceManager.GetString("DeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El elemento fue removido correctamente..
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El elemento ya existe en la base de datos..
        /// </summary>
        public static string DeniedRegistration {
            get {
                return ResourceManager.GetString("DeniedRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al exportar la información. Por favor intente de nuevo..
        /// </summary>
        public static string ErrorExportList {
            get {
                return ResourceManager.GetString("ErrorExportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del campo {0} debe ser mayor a {1}.
        /// </summary>
        public static string GreaterThanMessage {
            get {
                return ResourceManager.GetString("GreaterThanMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El identificador es obligatorio.
        /// </summary>
        public static string Id_Field_Not_Null {
            get {
                return ResourceManager.GetString("Id_Field_Not_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código ingresado no es válido.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del campo {0} debe ser mayor o igual a {1} y menor o igual a {2}.
        /// </summary>
        public static string InvalidEqualRangeMessage {
            get {
                return ResourceManager.GetString("InvalidEqualRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} no tiene formato correcto.
        /// </summary>
        public static string InvalidFormatMessage {
            get {
                return ResourceManager.GetString("InvalidFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe contener como mínimo {1}  y máximo  {2} caracteres.
        /// </summary>
        public static string InvalidRangeLengthMessage {
            get {
                return ResourceManager.GetString("InvalidRangeLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del campo {0} debe ser mayor a {1} y menor a {2}.
        /// </summary>
        public static string InvalidRangeMessage {
            get {
                return ResourceManager.GetString("InvalidRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El elemento no fue encontrado..
        /// </summary>
        public static string ItemNotFoundMessage {
            get {
                return ResourceManager.GetString("ItemNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario o contraseña es incorrecto..
        /// </summary>
        public static string LoginFailMessage {
            get {
                return ResourceManager.GetString("LoginFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso exitoso.
        /// </summary>
        public static string ProcessSuccess {
            get {
                return ResourceManager.GetString("ProcessSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de caracteres del campo {0} debe estar entre {1} y {2}.
        /// </summary>
        public static string PropertyBetweenLengthMessage {
            get {
                return ResourceManager.GetString("PropertyBetweenLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe tener un máximo de 15 dígitos en la parte entera y 2 dígitos en la parte decimal.
        /// </summary>
        public static string PropertyDecimalFormatCorrect {
            get {
                return ResourceManager.GetString("PropertyDecimalFormatCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del campo {0} debe ser mayor ó igual a {1}.
        /// </summary>
        public static string PropertyGreatherThanOrEqualMessage {
            get {
                return ResourceManager.GetString("PropertyGreatherThanOrEqualMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del campo {0} debe ser menor ó igual a {1}.
        /// </summary>
        public static string PropertyLessThanOrEqualMessage {
            get {
                return ResourceManager.GetString("PropertyLessThanOrEqualMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe contener como máximo {1} caracteres.
        /// </summary>
        public static string PropertyMaxLengthMessage {
            get {
                return ResourceManager.GetString("PropertyMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe contener como minimo {1} caracteres.
        /// </summary>
        public static string PropertyMinLengthMessage {
            get {
                return ResourceManager.GetString("PropertyMinLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un registro para este campo, {1}.
        /// </summary>
        public static string PropertyNoEqualMessage {
            get {
                return ResourceManager.GetString("PropertyNoEqualMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} no puede estar en blanco .
        /// </summary>
        public static string PropertyNotNullMessage {
            get {
                return ResourceManager.GetString("PropertyNotNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} solo permite caracteres numéricos.
        /// </summary>
        public static string PropertyOnlyNumericMessage {
            get {
                return ResourceManager.GetString("PropertyOnlyNumericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El token no se puede refrescar.
        /// </summary>
        public static string RefreshTokenFail {
            get {
                return ResourceManager.GetString("RefreshTokenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error actualizando el elemento. Por favor intente de nuevo..
        /// </summary>
        public static string UpdateErrorMessage {
            get {
                return ResourceManager.GetString("UpdateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El elemento fue actualizado correctamente..
        /// </summary>
        public static string UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no tiene permiso para realizar esta acción.
        /// </summary>
        public static string UserAccessDenied {
            get {
                return ResourceManager.GetString("UserAccessDenied", resourceCulture);
            }
        }
    }
}
